playerSkins = {
    {id = 0, name = "Claude"},
    {id = 1, name = "Police Officer #1", disable = true},
    {id = 2, name = "SWAT Officer"},
    {id = 3, name = "FBI Agent"},
    {id = 4, name = "Army Soldier"},
    {id = 5, name = "Paramedic"},
    {id = 6, name = "Firefighter"},
    {id = 7, name = "Wise Guy"},
    {id = 8, name = "Taxi Driver"},
    {id = 9, name = "Pimp"},
    {id = 10, name = "Mafia Member #1"},
    {id = 11, name = "Mafia Member #2"},
    {id = 12, name = "Triad Member #1"},
    {id = 13, name = "Triad Member #2"},
    {id = 14, name = "Diablo Member #1"},
    {id = 15, name = "Diablo Member #2"},
    {id = 16, name = "Yakuza Member #1"},
    {id = 17, name = "Yakuza Member #2"},
};